### ISSUE TITLE
separating tags and schemas

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx#187]
A quick thought about how to (maybe) handle the problem of inheritance from tags mentioned in #181 

### Problem
when inheriting schemas using `$ref` an already existing `tag` will be inherited too, making it infeasible to define a new tag (we should verify this soon 😉 -> tested: **doesn't work**, old tag does not get overwritten)

### Idea
split definitions into two files when necessary
- first file contains the ASDF schema definition and is saved as `name-1.0.0.schema.yaml`
- second file only contains the `tag` and a `$ref` to the actual schema and saved as `name-1.0.0.yaml`

### Example
`VGroove-1.0.0.schema.yaml`
```yaml
%YAML 1.1
---
$schema: "http://stsci.edu/schemas/yaml-schema/draft-01"
id: "http://weldx.bam.de/schemas/weldx/groove/iso_9692_1_2013_12/VGroove-1.0.0.schema"

title: |
  VGroove representation.

type: object
properties:
  t:
    description: |
      The workpiece thickness.
    $ref: "../terms-1.0.0#/definitions/workpiece-thickness"
  alpha:
    description: |
      The full groove angle.
    $ref: "../terms-1.0.0#/definitions/groove-angle"
  b:
    description: |
      The root gap between both plates.
    $ref: "../terms-1.0.0#/definitions/root-gap"
  c:
    description: |
      The root face.
    $ref: "../terms-1.0.0#/definitions/root-face"
required: [t, alpha, b, c]
propertyOrder: [t, alpha, b, c]
...

```
`VGroove-1.0.0.yaml`
```yaml
%YAML 1.1
---
$schema: "http://stsci.edu/schemas/yaml-schema/draft-01"
id: "http://weldx.bam.de/schemas/weldx/groove/iso_9692_1_2013_12/VGroove-1.0.0"
tag: "tag:weldx.bam.de:weldx/groove/iso_9692_1_2013_12/VGroove-1.0.0"

$ref: http://weldx.bam.de/schemas/weldx/groove/iso_9692_1_2013_12/VGroove-1.0.0.schema
...
```

### caveats
- This would basically break the documentation build. For this special case where the tag only contains a `$ref` we might be able to adapt `sphinx-asdf` to build build the description form the ref instead
- ~~also not sure if this even works as intended 🤔~~ **tested: it works** 😃
