### ISSUE TITLE
how to handle user metadata support for all objects

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx#205]
Now that quality standards are on their way 🚀 we should discuss how to support/implement additional user requirements to schemas.
Restricting or changing existing schema requirements should be straight forward by replacing the schema mappings, but what about adding new fields etc. ? The problem I see here is that by default, the weldx implemented `to_tree` methods would not know about additional fields to serialize even if these were added as attributes of a class.

I think we could do something similar to what `xarray` does with `.attrs`. Define a `WeldxBase` class with a designated attribute (suppose `metadata` oder `userdata`) that can hold a dict. This would be the place for users to store any kind of object they want to serialize with this specific instance.

Now if a user wants to define their own standard with completely different metadata fields (think standard definitions for internal workflows) they could implement this on the `metadata` property without affecting or having to change anything on the python side.

```yaml
# example for a standard requiring a metadata field for "arrangement"
properties:
  metadata:
    type: object
    properties:
      arrangement:
        description: camera arrangement layout
        type: string
        enum: [linear, circular]
    requiredProperties: [arrangement]
```

### how could we make this work?
I think it would be cumbersome and error prone to implement the serialization of the `metadata` attribute in every single `to_tree` method by hand. Instead we should define a base (meta)class that dynamically applies the necessary changes to the `to_tree` method after class creation. We could also use a class decorator similar to here for this but I think defining a more general metaclass might have other uses down the line.
Or maybe there is a simpler way?

### schema considerations
While the Python side should be quite flexible, the ASDF schemas in this regard are rather not. Two possibilities:
1. add a `metadata` property to every single schema.
1. remove `additionalProperties: true` from schemas where it is set
1. the mixer: only add the `metadata` property in schemas where we absolutely need `additionalProperties: true`
