### ISSUE TITLE
custom ASDF validators

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx#40]
some thoughts and ideas regarding implementations of custom ASDF validators

## handling $ref
any validation keywords that are on the level of a $ref: statement seem to be dropped (validation does not get triggerd)
example:
```yaml
properties:
  length_prop:
    $ref: tag:stsci.edu:asdf/unit/quantity-1.1.0
    wx_unit: "s" # this does not trigger a validator on wx_unit
wx_unit:
  length_prop: "m" # this works as expected
```
See https://github.com/asdf-format/asdf/issues/814 for details and workaround using `tag` validator

```yaml
type: object
properties:
  quantity_prop:
    description: |
      a simple quantity with custom validator
    tag: tag:stsci.edu:asdf/unit/quantity-1.1.0
    wx_unit: "s"
```

## registering validators
apparently registering a validator for one class might enable the validator on a global extension level. This might be useful  but we should check "overriding" validator keywords with different functions for seperate classes.

See https://github.com/asdf-format/asdf/issues/815#issuecomment-651132226 for explanation of current implementation

## handling `anyOf` / `oneOf`
**UPDATE:** this was fixed by defining better (tighter) restrictions on `anyOf` subtypes (i.e. well defined `required` with `additionalProperties: false`)
Use of `oneOf` is encouraged once https://github.com/asdf-format/asdf/pull/811 is available (see https://github.com/asdf-format/asdf/issues/809)
