### ISSUE TITLE
set default inline threshold

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx#601]
I think it would make sense to set a (sensible) default threshold to inline array values for most of our use cases

I think 10 should be a good value because it will inline a single (static) 3x rotation matrix and short list of vectors e.g. movements between two points
```yaml
coordinates: !weldx!core/variable-0.1.0
    name: coordinates
    dimensions: [time, c]
    dtype: <f8
    data: !core/ndarray-1.0.0
      data:
      - [20.0, 0.0, 3.0]
      - [330.0, 0.0, 3.0]
      datatype: float64
      shape: [2, 3]
```
