### ISSUE TITLE
add property type/tag validator for yaml objects

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx#66]
With the `array` keyword python lists can be restricted to contain a single type in asdf:
```yaml
  coordinates:
    description: |
      An array of variables that represent coordinates.
    type: array
    items:
      $ref: "tag:weldx.bam.de:weldx/core/variable-1.0.0" # only variable-1.0.0 objects allowed as list items
```
```yaml
# asdf file
coordinates:
- !<tag:weldx.bam.de:weldx/core/variable-1.0.0>
  name: c
  data: [x,y,z]
- !<tag:weldx.bam.de:weldx/core/variable-1.0.0>
  name: v
  data: [0,1,2]
```

The advantage when using `array` is that the count of items is flexible. But to identify the list items some extra metadata like `name` might be required.

In these cases, having key - value pairs like with `object` (`dict`) might be preferable. Currently, property types can only be restricted if the property is defined inside the asdf schema in advance. For fully flexible python dicts this is not possible.

For the simple use case of implementing a key-value mapping with restricted value types we could implement a new validator that checks if all properties have a specific tag.

```yaml
  coordinates:
    description: |
      An key-value mapping of variables that represent coordinates.
    type: object
    additionalProperties: true
    wx_property_tag: "tag:weldx.bam.de:weldx/core/variable-1.0.0"
```
```yaml
# asdf file
coordinates:
  c: !<tag:weldx.bam.de:weldx/core/variable-1.0.0>
    data: [x,y,z]
  v: !<tag:weldx.bam.de:weldx/core/variable-1.0.0>
    data: [0,1,2]
```
