### ISSUE TITLE
custom tag validation with version support

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx#98]
implement a custom `wx_tag` validation that supports simple versioning conventions (until implemented within ASDF)

```yaml
wx_tag: http://stsci.edu/schemas/asdf/core/software-* # allow every version
wx_tag: http://stsci.edu/schemas/asdf/core/software-1 # fix major version
wx_tag: http://stsci.edu/schemas/asdf/core/software-1.2 # fix minor version
wx_tag: http://stsci.edu/schemas/asdf/core/software-1.2.3 # fix patchversion
```
